-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK.AUTHOR_ID, CATEGORY
ORDER BY BOOK.AUTHOR_ID, CATEGORY DESC