-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, FLOOR(DAILY_FEE * 30 * ((100 - DISCOUNT_RATE)/100)) AS FEE
FROM (
SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, DISCOUNT_RATE,DAILY_FEE 
FROM CAR_RENTAL_COMPANY_CAR 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN ON CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE = CAR_RENTAL_COMPANY_CAR.CAR_TYPE
WHERE (CAR_RENTAL_COMPANY_CAR.CAR_TYPE IN ('세단','SUV')) AND 
    (CAR_RENTAL_COMPANY_CAR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01' )) AND
    (DURATION_TYPE = '30일 이상')
) A
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC