-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
From ANIMAL_OUTS 
WHERE ANIMAL_OUTS.ANIMAL_ID NOT IN 
(SELECT ANIMAL_OUTS.ANIMAL_ID
 FROM ANIMAL_OUTS JOIN ANIMAL_INS ON  ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID)