-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND( ((DATEDIFF(END_DATE,START_DATE)+1) * DAILY_FEE ) * @RATE := (
    SELECT
    CASE
        WHEN DATEDIFF(END_DATE,START_DATE)+1 < 7
            THEN 1
        WHEN DATEDIFF(END_DATE,START_DATE)+1 < 30 AND DATEDIFF(END_DATE,START_DATE)+1 >= 7
            THEN 0.95
        WHEN DATEDIFF(END_DATE,START_DATE)+1 < 90 AND DATEDIFF(END_DATE,START_DATE)+1 >= 30
            THEN 0.92
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90
            THEN 0.85   
        END
    ), 0) FEE
FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN ON CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE = CAR_RENTAL_COMPANY_CAR.CAR_TYPE
WHERE CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC